version: '3.8'

services:
  angularapp-server:
    build:
      context: .
      dockerfile: AngularApp1.Server/Dockerfile
    ports:
      - "5043:8080"  # Maps to the exposed port 8080

  angularapp-client:
    build:
      context: ./angularapp1.client
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - angularapp-server